FORMAT: 1A
HOST: http://localhost:8080/api

# RouteMe-API

A JSON-Based RESTful API for the RouteME collaborative multi-modal
route recommender app. This API is build as a backend support for
the prototype iOS app RouteMe which is developed as a prototype
to support the research of my Master thesis topic which is
"Collaborative and Social Multi-modal Route Planning"



## Registration [/users]


### Signup [POST]


+ Request (application/json)

        {
            "username": "heshammassoud",
            "email": "heshamhamdymassoud@gmail.com",
            "password": "LimpBizkit22!",
            "confirmationPassword": "LimpBizkit22!"
        }

+ Response 201 (application/json)

    + Body

            {
                "id": "123",
                "username": "heshammassoud",
                "email": "heshamhamdymassoud@gmail.com",
                "password": "LimpBizkit22!",
                "confirmationPassword": "LimpBizkit22!"
            }

## Authentication [/users/{id}/login]

### login [POST]

+ Request (application/json)

        {
            "email": "heshamhamdymassoud@gmail.com",
            "password": "LimpBizkit22!",
        }

+ Response 200 (application/json)

    + Body
    
            {
                "e-mail": "heshamhamdymassoud@gmail.com",
                "password": "LimpBizkit22",
            }

## Preferences [/users/{id}/preferences]

### Set travel preferencs [PUT]

+ Request (application/json)

        {
            "travelModePreferences": [
                "driving",
                "transit",
                "walking",
                "bicycling"
                ],
            "transitRouteTypePreference": [
                "leastChanges",
                "leastTime"
                ]
        }

+ Response 200 (application/json)

    + Body
    
            {
                "travelModePreferences": [
                    "driving",
                    "transit",
                    "walking",
                    "bicycling"
                    ],
                "transitRouteTypePreference": [
                    "leastChanges",
                    "leastTime"
                     ]
            }